//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS_Filter_Customizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS_Filter_Customizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultFilterProfileDetailed {
            get {
                return ResourceManager.GetString("DefaultFilterProfileDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultFilterProfileFullControl {
            get {
                return ResourceManager.GetString("DefaultFilterProfileFullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;type&gt;0&lt;/type&gt;
        ///  &lt;filters&gt;
        ///    &lt;filter world=&quot;-1&quot; id=&quot;-1&quot;&gt;
        ///      &lt;brightness sync=&quot;false&quot;&gt;1,1,1&lt;/brightness&gt;
        ///      &lt;contrast sync=&quot;false&quot;&gt;1,1,1&lt;/contrast&gt;
        ///      &lt;saturation&gt;1&lt;/saturation&gt;
        ///      &lt;hue&gt;0&lt;/hue&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/filters&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string DefaultFilterProfileGlobal {
            get {
                return ResourceManager.GetString("DefaultFilterProfileGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;type&gt;1&lt;/type&gt;
        ///  &lt;filters&gt;
        ///    &lt;filter world=&quot;-1&quot; id=&quot;-1&quot;&gt;
        ///      &lt;brightness sync=&quot;false&quot;&gt;1,1,1&lt;/brightness&gt;
        ///      &lt;contrast sync=&quot;false&quot;&gt;1,1,1&lt;/contrast&gt;
        ///      &lt;saturation&gt;1&lt;/saturation&gt;
        ///      &lt;hue&gt;0&lt;/hue&gt;
        ///    &lt;/filter&gt;
        ///  &lt;/filters&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string DefaultFilterProfileMultiplier {
            get {
                return ResourceManager.GetString("DefaultFilterProfileMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FilterDetailedLookup {
            get {
                return ResourceManager.GetString("FilterDetailedLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10,2  The Depths
        ///10,10 Undead Burg/Parish - Exterior
        ///10,11 Undead Burg/Parish - Interior
        ///10,20 Firelink Shrine
        ///
        ///11,0  Painted World
        ///
        ///12,0  Darkroot Garden/Basin
        ///12,11 Oolacile Sanctuary/Township - Exterior
        ///12,12 Oolacile Sanctuary/Township - Interior
        ///12,17 Chasm of the Abyss
        ///12,20 Royal Wood
        ///
        ///13,0  Catacombs
        ///13,5  Great Hollow
        ///13,13 Tomb of the Giants - Exterior
        ///13,14 Tomb of the Giants - Interior
        ///13,18 Ash Lake
        ///
        ///14,2  Blighttown
        ///14,5  Quelaag&apos;s Domain
        ///14,6  Demon Ruins
        ///14,15 Lost Izal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilterDetailedNames {
            get {
                return ResourceManager.GetString("FilterDetailedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10,1  The Depths - Entrance
        ///10,2  The Depths - General
        ///10,3  The Depths - Sewers
        ///10,4  The Depths - Gaping Dragon
        ///10,10 Undead Burg/Parish - Exterior
        ///10,11 Undead Burg/Parish - Interior
        ///10,20 Firelink Shrine - General
        ///10,23 Firelink Shrine - To Catacombs
        ///10,24 Firelink Shrine - To New Londo
        ///
        ///11,0  Painted World - General
        ///11,1  Painted World - Priscilla
        ///11,2  Painted World - Exit
        ///
        ///12,0  Darkroot Garden/Basin
        ///12,11 Oolacile - Exterior
        ///12,12 Oolacile - Interior
        ///12,17 Chasm of the Abyss
        ///12,20  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilterFullControlNames {
            get {
                return ResourceManager.GetString("FilterFullControlNames", resourceCulture);
            }
        }
    }
}
